### ISSUE TITLE
Support Android client certificates

### ISSUE THREAD

**Issue by alesnav** [repat/miniflux-embedded-android#1]
Hello!

@repat it would be nice it the app supports client certificates to authenticate on the miniflux server. Do you think it is possible?

Thanks!

Maybe this link can help: http://stackoverflow.com/questions/7714993/https-connection-with-client-certificate-in-an-android-app

**Comment by repat** [comment]
That depends a little bit on how complicated the implementation is;) Also, I have no way to test this.

What's the error message you get?
